title: "jpda.dev"
description: "cloud bits and bobs"
author_name: "jpda"
logo_url: https://avatars2.githubusercontent.com/u/5932293?v=4

twitter:
  username: azureandchill
  card: summary

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: https://avatars2.githubusercontent.com/u/5932293?v=4
      

remote_theme: heiswayi/the-plain
url: https://jpda.dev
permalink: /:title
timezone: America/New_York
mathjax: false

appInsights: true
appInsightsKey: "aa50374c-4629-4ab3-a058-5bb4d8bb1924"
fontawesome: false
resume_url: "img/file-pngrepo-com.png"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag